server:
  port: 8088

spring:
  docker:
    compose:
      enabled: false
  data:
    redis:
      host: 110.41.166.11
      port: 6379
      password: 20230607
      database: 0
      lettuce:
        pool:
          max-active: 8
  datasource:
    url: jdbc:mysql://110.41.166.11:3306/bcnl?useSSL=false&allowPublicKeyRetrieval=true
    username: failedman
    password: 20230607
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    filter:
      order: -100
    jwt:
      key: abcdefghijk
      expire: 7
  mail:
    host: smtp.163.com
    username: linxy20040304@163.com
    password: PXILBFPDDKSNRFAI
  rabbitmq:
    addresses: 110.41.166.11:5672
    username: failedman
    password: 20230607
    virtual-host: /

springdoc:
  swagger-ui:
    path: /doc/ui
  api-docs:
    path: /doc/json
